### ISSUE TITLE
Gem broken on Ruby 3.2 due to removal of rb_obj_infect

### ISSUE THREAD

**Issue by ivoanjo** [dearblue/ruby-extlz4#4]
Hello there, and thanks for this cool gem! I'm using it for testing compressed outputs in @Datadog's [ddtrace gem](https://github.com/DataDog/dd-trace-rb).

Since Ruby 2.7 (https://github.com/ruby/ruby/pull/2476) the `rb_obj_infect` API has not done anything and just emits a deprecation warning.

But Ruby 3.2 is finally upon us and in https://github.com/ruby/ruby/pull/5348 the API was actually removed, so this gem does not work 3.2.0-preview1/3.2.0-preview2.

**Comment by dearblue** [comment]
Thank you for your report!
I'm Japanese, so I pretended I didn't understand the warning written in English. :scream_cat:
Anyhow, I will check with Ruby-3.2 preview2 and release a new version probably tomorrow or the day after.
Please give me some time.

Also, I will release a new version which includes lz4-1.9.4 in the near future. Probably.......

**Comment by ivoanjo** [comment]
> I'm Japanese, so I pretended I didn't understand the warning written in English. 🙀

😉😉😉 

Thanks a lot for looking into this 🙇

**Comment by dearblue** [comment]
I have released a new version as extlz4-0.3.3.
I am closing this issue ahead of time, but if you have any problems, please do not hesitate to contact me for feedback.

**Comment by ivoanjo** [comment]
Thanks a lot! I can confirm it's now working fine -- I'm using it in https://github.com/DataDog/dd-trace-rb/pull/2302 and CI is looking good for 3.2 :)
